name: sakou_xam_xam
description: "A new Flutter project for interactive learning."

# Empêche la publication accidentelle sur pub.dev.
publish_to: 'none'

# Version de l'application.
version: 1.0.0+1

# Environnement Dart SDK requis.
environment:
  sdk: ">=3.6.0 <4.0.0"

# Dépendances nécessaires à l'application.
dependencies:
  flutter:
    sdk: flutter

  # Icônes style iOS.
  cupertino_icons: ^1.0.8

  # Ajouter Firebase.
  firebase_core: ^2.13.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0
  firebase_storage: ^11.0.4
  webviewx: ^0.2.2
  file_picker: ^5.3.3

  # Gestion des requêtes HTTP.

  # Gestion des états avec BLoC.
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5

  # Pour les dates et formats.
  intl: ^0.18.0

  # Gestion des fichiers et images.

  # Utilisation de variables d'environnement.
  flutter_dotenv: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Section pour les ressources.
  assets:
    - assets/img/

  # Exemple d'ajout de polices personnalisées.

